//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freedom.ZHPHMachine.ViewModels {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TipMsgResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TipMsgResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Freedom.ZHPHMachine.ViewModels.TipMsgResource", typeof(TipMsgResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 您所选择的户口所在地与人口库不符合，请再次确认无误！ 的本地化字符串。
        /// </summary>
        internal static string AddressTipMsg {
            get {
                return ResourceManager.GetString("AddressTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前证件已过期失效，请选择[失效重新申领] 的本地化字符串。
        /// </summary>
        internal static string DocumentExpirationTipMsg {
            get {
                return ResourceManager.GetString("DocumentExpirationTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前证件有效期小于半1年，默认只能办理[3个月一次] 的本地化字符串。
        /// </summary>
        internal static string DocumentGAYearTipMsg {
            get {
                return ResourceManager.GetString("DocumentGAYearTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前证件有效期小于3个月零30天，不能选择[3个月一次]，请选择[遗失补发]或[到期换发] 的本地化字符串。
        /// </summary>
        internal static string DocumentMonthTipMsg {
            get {
                return ResourceManager.GetString("DocumentMonthTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前证件有效期小于半1年，默认只能办理[6个月一次] 的本地化字符串。
        /// </summary>
        internal static string DocumentTWNYearTipMsg {
            get {
                return ResourceManager.GetString("DocumentTWNYearTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前证件有效期大于当前日期，不能选择[首次申请] 或[失效重新申领],请选择其它办证类别 的本地化字符串。
        /// </summary>
        internal static string DocumentValidTipMsg {
            get {
                return ResourceManager.GetString("DocumentValidTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择的办证类型与仅签注业务冲突，请重新选择！ 的本地化字符串。
        /// </summary>
        internal static string DQZMsg {
            get {
                return ResourceManager.GetString("DQZMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未查询到您的证件信息，不能选择其它办证类型，请选择[首次申请] 的本地化字符串。
        /// </summary>
        internal static string FirstApplyTipMsg {
            get {
                return ResourceManager.GetString("FirstApplyTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份核验发生异常，请重试！（G） 的本地化字符串。
        /// </summary>
        internal static string GJGWRYExceptionTipMsg {
            get {
                return ResourceManager.GetString("GJGWRYExceptionTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您不符合自助办理条件，不能取号，若有疑问，请移步人工窗口咨询!（G） 的本地化字符串。
        /// </summary>
        internal static string GJGWRYTipMsg {
            get {
                return ResourceManager.GetString("GJGWRYTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序发生严重异常,请联系工作人员处理。 的本地化字符串。
        /// </summary>
        internal static string GlobalExceptionTipMsg {
            get {
                return ResourceManager.GetString("GlobalExceptionTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的户口不是深圳户籍，不能办理一年多次签注，请重新选择！ 的本地化字符串。
        /// </summary>
        internal static string HKGErrorTipMsg {
            get {
                return ResourceManager.GetString("HKGErrorTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通护照中请填写至少一条加注事由 的本地化字符串。
        /// </summary>
        internal static string HZAddApplyTipMsg {
            get {
                return ResourceManager.GetString("HZAddApplyTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证号码有误，请您重新输入 的本地化字符串。
        /// </summary>
        internal static string IDCardErrorTipMsg {
            get {
                return ResourceManager.GetString("IDCardErrorTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化身份证阅读器失败,请检查接线或重启软件 的本地化字符串。
        /// </summary>
        internal static string IDCardInitializationTipMsg {
            get {
                return ResourceManager.GetString("IDCardInitializationTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证不能为空或格式错误，请重新填写 的本地化字符串。
        /// </summary>
        internal static string IDCardNonEmptyTipMsg {
            get {
                return ResourceManager.GetString("IDCardNonEmptyTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核对身份信息中，请等待... 的本地化字符串。
        /// </summary>
        internal static string IDCardQuueryTipMsg {
            get {
                return ResourceManager.GetString("IDCardQuueryTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份核验失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string IdentityErrorTipMsg {
            get {
                return ResourceManager.GetString("IdentityErrorTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未查到人口信息：身份核验失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string IdentityExceptionTipMsg {
            get {
                return ResourceManager.GetString("IdentityExceptionTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择至少一种办证类型 的本地化字符串。
        /// </summary>
        internal static string NonEmptySelectsTipMsg {
            get {
                return ResourceManager.GetString("NonEmptySelectsTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择有效的预约时间段 的本地化字符串。
        /// </summary>
        internal static string NonEmptySelectTipMsg {
            get {
                return ResourceManager.GetString("NonEmptySelectTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能为空，请重新填写 的本地化字符串。
        /// </summary>
        internal static string NonEmptyTipMsg {
            get {
                return ResourceManager.GetString("NonEmptyTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化打印机失败,请检查接线或重启软件 的本地化字符串。
        /// </summary>
        internal static string PrintInitializationTipMsg {
            get {
                return ResourceManager.GetString("PrintInitializationTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的申请类型已选择仅签注，办证类别请选择[持证申请签注] 的本地化字符串。
        /// </summary>
        internal static string QZTipMsg {
            get {
                return ResourceManager.GetString("QZTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您扫描或手输入的相片回执格式不正确，请重新操作！ 的本地化字符串。
        /// </summary>
        internal static string ScanningReceiptErrorTipMsg {
            get {
                return ResourceManager.GetString("ScanningReceiptErrorTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化扫描枪失败,请检查接线或重启软件 的本地化字符串。
        /// </summary>
        internal static string ScanningReceiptTipMsg {
            get {
                return ResourceManager.GetString("ScanningReceiptTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份核验发生异常，请重试！（S） 的本地化字符串。
        /// </summary>
        internal static string SKDXExceptionTipMsg {
            get {
                return ResourceManager.GetString("SKDXExceptionTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您不符合自助办理条件，不能取号，若有疑问，请移步人工窗口咨询!（S） 的本地化字符串。
        /// </summary>
        internal static string SKDXTipMsg {
            get {
                return ResourceManager.GetString("SKDXTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作超时，现在返回首页请重新操作！ 的本地化字符串。
        /// </summary>
        internal static string TimeOutTipMsg {
            get {
                return ResourceManager.GetString("TimeOutTipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的申请类型已选择仅通行证，不能选择[持证申请签注]，请选择其它办证类别 的本地化字符串。
        /// </summary>
        internal static string TXZTipMsg {
            get {
                return ResourceManager.GetString("TXZTipMsg", resourceCulture);
            }
        }
    }
}
